---
- name: configure ssh connection
  hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: test ~/.ssh/*
      shell: |
        if ! [ -f ~/.ssh/id_rsa ];then ssh-keygen -f /root/.ssh/id_rsa -N '';fi
    - name: configure ssh connection
      shell: |
        ssh-keyscan {{inventory_hostname}} >>~/.ssh/known_hosts
        sshpass -p '{{ ansible_password }}' ssh-copy-id -p {{ ansible_port }} {{ ansible_user }}@{{inventory_hostname}}

- name: Partition formatting mount disk
  hosts: all
  tasks:
  - name: u'未分区磁盘'
    parted: device=/dev/{{item.key}} number=1 state=present
    when:
      - not item.value.partitions
      - item.key is match ("sd.*") or item.key is match ("vd.*")
    register: status
    with_dict: "{{ ansible_devices }}"

  - name: u'格式化磁盘'
    filesystem: dev=/dev/{{ item.item.key }}1 fstype=xfs
    when: item.changed != false
    with_items: "{{ status.results }}"

  - name: u'挂载'
    mount:
      path: /opt
      src: /dev/{{ item.item.key }}1
      fstype: xfs
      state: mounted
    when: item.changed != false
    with_items: "{{ status.results }}"
