---
- name: modify limit
  blockinfile:
    path: /etc/security/limits.conf
    block: |
      * soft nofile 65535
      * hard nofile 65535
      * soft nproc  2066336
      * hard nproc  2066336
      * soft memlock unlimited
      * hard memlock unlimited
    state: present

- name: Add fs.file-max /etc/sysctl.conf
  lineinfile:
    path: /etc/sysctl.conf
    regexp: "^{{ item.regexp }}"
    line: "{{ item.lineinfile }}"
    state: present
  loop:
    - regexp: fs.file-max
      lineinfile: fs.file-max = 6553560
    - regexp: fs.inotify.max_user_watches
      lineinfile: fs.inotify.max_user_watches = 8192000
    - regexp: net.core.netdev_max_backlog
      lineinfile: net.core.netdev_max_backlog = 262144
    - regexp: net.core.rmem_max
      lineinfile: net.core.rmem_max = 16777216
    - regexp: net.core.somaxconn
      lineinfile: net.core.somaxconn = 65535
    - regexp: net.core.wmem_max
      lineinfile: net.core.wmem_max = 16777216
    - regexp: net.ipv4.conf.all.accept_redirects
      lineinfile: net.ipv4.conf.all.accept_redirects = 0
    - regexp: net.ipv4.conf.all.arp_announce
      lineinfile: net.ipv4.conf.all.arp_announce = 2
    - regexp: net.ipv4.conf.all.arp_ignore
      lineinfile: net.ipv4.conf.all.arp_ignore = 1
    - regexp: net.ipv4.conf.all.log_martians
      lineinfile: net.ipv4.conf.all.log_martians = 1
    - regexp: net.ipv4.conf.all.secure_redirects
      lineinfile: net.ipv4.conf.all.secure_redirects = 0
    - regexp: net.ipv4.conf.default.accept_redirects
      lineinfile: net.ipv4.conf.default.accept_redirects = 0
    - regexp: net.ipv4.conf.default.secure_redirects
      lineinfile: net.ipv4.conf.default.secure_redirects = 0
    - regexp: net.ipv4.conf.lo.arp_announce
      lineinfile: net.ipv4.conf.lo.arp_announce = 2
    - regexp: net.ipv4.conf.lo.arp_ignore
      lineinfile: net.ipv4.conf.lo.arp_ignore = 1
    - regexp: net.ipv4.icmp_echo_ignore_broadcasts
      lineinfile: net.ipv4.icmp_echo_ignore_broadcasts = 1
    - regexp: net.ipv4.icmp_ignore_bogus_error_responses
      lineinfile: net.ipv4.icmp_ignore_bogus_error_responses = 1
    - regexp: net.ipv4.ip_forward
      lineinfile: net.ipv4.ip_forward = 1
    - regexp: net.ipv4.ip_local_port_range
      lineinfile: net.ipv4.ip_local_port_range = 1024 65535
    - regexp: net.ipv4.tcp_fin_timeout
      lineinfile: net.ipv4.tcp_fin_timeout = 30
    - regexp: net.ipv4.tcp_keepalive_intvl
      lineinfile: net.ipv4.tcp_keepalive_intvl = 5
    - regexp: net.ipv4.tcp_keepalive_probes
      lineinfile: net.ipv4.tcp_keepalive_probes = 2
    - regexp: net.ipv4.tcp_keepalive_time
      lineinfile: net.ipv4.tcp_keepalive_time = 60
    - regexp: net.ipv4.tcp_max_orphans
      lineinfile: net.ipv4.tcp_max_orphans = 3276800
    - regexp: net.ipv4.tcp_max_syn_backlog
      lineinfile: net.ipv4.tcp_max_syn_backlog = 262144
    - regexp: net.ipv4.tcp_max_tw_buckets
      lineinfile: net.ipv4.tcp_max_tw_buckets = 30000
    - regexp: net.ipv4.tcp_no_metrics_save
      lineinfile: net.ipv4.tcp_no_metrics_save = 1
    - regexp: net.ipv4.tcp_retries2
      lineinfile: net.ipv4.tcp_retries2 = 5
    - regexp: net.ipv4.tcp_rmem
      lineinfile: net.ipv4.tcp_rmem = 4096 87380 16777216
    - regexp: net.ipv4.tcp_wmem
      lineinfile: net.ipv4.tcp_wmem = 4096 87380 16777216
    - regexp: net.ipv4.tcp_mem
      lineinfile: net.ipv4.tcp_mem = 786432 2097152 3145728
    - regexp: net.ipv4.tcp_sack
      lineinfile: net.ipv4.tcp_sack = 1
    - regexp: net.ipv4.tcp_synack_retries
      lineinfile: net.ipv4.tcp_synack_retries = 2
    - regexp: net.ipv4.tcp_syncookies
      lineinfile: net.ipv4.tcp_syncookies = 1 
    - regexp: net.ipv4.tcp_syn_retries
      lineinfile: net.ipv4.tcp_syn_retries = 2
    - regexp: net.ipv4.tcp_timestamps
      lineinfile: net.ipv4.tcp_timestamps = 0
    - regexp: net.ipv4.tcp_tw_recycle
      lineinfile: net.ipv4.tcp_tw_recycle = 1
    - regexp: net.ipv4.tcp_tw_reuse
      lineinfile: net.ipv4.tcp_tw_reuse = 1
    - regexp: net.ipv4.tcp_window_scaling
      lineinfile: net.ipv4.tcp_window_scaling = 1
    - regexp: vm.overcommit_memory
      lineinfile: vm.overcommit_memory = 1
    - regexp: vm.max_map_count
      lineinfile: vm.max_map_count = 262144
    - regexp: vm.swappiness
      lineinfile: vm.swappiness = 0
  notify: sysctl

- name: add harbor dns
  lineinfile:
    path: /etc/hosts
    line: 45.120.243.50 harbor.teleinfo.cn
